"""Initial migration - Create all tables

Revision ID: 001
Revises:
Create Date: 2024-11-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # This is auto-generated by Alembic when you run: alembic revision --autogenerate -m "Initial migration"
    pass


def downgrade() -> None:
    """Downgrade database schema"""
    pass
